---
functional:
  - Просмотр товаров в каталоге
  - Фильтрация товаров
  - Добавление товаров в корзину
  - Просмотр подробной информации о товаре
  - Отображение названия, рейтинга, цены со скидкой и без на странице товара и в каталоге  
  - Удаление товара из корзины
  - Оформление заказа с переходом на страницу оплаты
  - Поиск товаров по ключевому слову или категории
  - Хранение корзины в сессии браузера
  - Переключение языка интерфейса

non-functional:
  - Адаптивная верстка для мобильных устройств
  - Одностраничное приложение без перезагрузки страницы
  - Постраничный вывод товаров
  - Оптимизация для скорости работы
  - Безопасность и защита данных пользователя
  - Совместимость с последними версиями браузеров
  - Обработка большого количества трафика
  - Доступность на различных устройствах
  - Доступность без VPN из сети Интернет
  - Хранение корзины в сессии браузера 

implicit:
  - Корректный расчет цен со скидкой в корзине
  - Возможность изменения количества товара в корзине
  - Сохранение фильтров и поиска при навигации
  - Индикация загрузки при медленном интернете
  - Валидация данных при оформлении заказа
  - Информирование об ошибках при добавлении товара
  - Подтверждение действий пользователя
